### ISSUE TITLE
The FileMaker challenge

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/Framework#16]
## Summary
In order to keep the FM interface while also modernizing the database structure, we have to investigate the implementation of FM as a direct interface to MySQL OR an intermediary model where there is tables replication on the FM server. Extended tests will be needed to check the speed of populating FM views and doing searches. 

This task is only about finding and testing the appropriate solution. Full implementation of the solution will happen only after DB design.

## Tasks

- [x] Read about FileMaker and MySQL 
- [x] Research about scenarios for using FM as the direct interface and MySQL as the master database
- [x] Connect FM with MySQL using External Data Source connection (ODBC connection)
- [x] Test the FM client and MySQL ESS connection 
- [ ] Connect FM Pro to the FM server and connect the server to the MySQL database using ESS
- [ ] Test the connection (also test for speed with relationships and large tables) 

#### 📈 Progress (0-1): 0.8

See Gantt: http://cdli-dev.org/gantt/Framework/
