### ISSUE TITLE
Prepare out-of-the-box controllers and views for all database tables and refine artifact single and list views

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/Framework#39]
## Summary
- [x] Using cakePHP's bake tool, generate the controllers and views for each of our data tables
- [ ] Make sure all objects can be properly viewed, created and edited
- [ ] Make sure an individual object display has all required information and links displaying properly
- [ ] Make sure the list of artifacts display has all required information and links displaying properly

## Roadmap Data
Should start as soon as the model layer is ready from #15 

#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/Framework/

**Comment by epageperron** [comment]
Blocked by #15

**Comment by epageperron** [comment]
The workflow is iterative so this issue is obsolete.
