### ISSUE TITLE
Prepare the VM install for production

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/Framework#71]
## Summary
The Docker deploy for the new VM of CDLI is ready but some functionalities need to be ported first before we can power down our physical servers.

## Other links or relevant information
- [ ] workflow to update the catalogue (currently run manually with a perl script) #76 
- [x] collections script #60 @Douglasli 
- [x] upload tool #70 @nonoon
- [ ] set up the dl and webroot directories on the CDH storage, make sure they are accessible to the VM and back them up on the Qnap
  - [ ] Rsync - DL, Webroot, Dump directories in 157 (this does not exist on 157 yet. test when this part comes on line) to QNAP. Tim will let us know when DL, Webroot, and Dump directories exist on 157 and copy data from 156 o 157. Then we will move forward with testing Rsync backup.
  - [ ] Maybe create as "Cold Storage" Volume for backups of DL, Webroot, and Dump directories for the future. This will create a one way path to store backups and not put it back into "live" data in the archivalfiles and rawfiles volumes.
- [ ] Fully test the VM on the UCLA server CDLI 157 (make it function like 156)
  - [x] Collections script work
  - [x] Uploads
       * etc
  - [ ] make sure the json service for cdli tablet (ipad & Android) work normally from the same url

#### 📈 Progress (0-1): 0

See Gantt: http://cdli-dev.org/gantt/Framework/

**Comment by epageperron** [comment]
Ticked the box for the upload script, thanks @nomoon !

**Comment by Obaid51** [comment]
Is this issue still available? Let me know if this is still available ?

**Comment by epageperron** [comment]
https://gitlab.com/cdli/framework/issues/106
